server:
  port: 5353
spring:
  application:
    name: freetime
  mvc:
    async:
      request-timeout: 180000
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-crj.cincpgqgykpl.ap-northeast-2.rds.amazonaws.com/freetime?&rewriteBatchedStatements=true
    username: jeekim
    password: wlzla01!
jwt:
  secret:
    key: freetime
