server:
  port: 5353
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: freetime
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-crj.cincpgqgykpl.ap-northeast-2.rds.amazonaws.com/freetime?&rewriteBatchedStatements=true
    username: jeekim
    password: wlzla01!
jwt:
  secret:
    key: freetime
springdoc:
  packages-to-scan: org.example.freetime.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
